name: java project
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: collecting the sourse code
        uses: actions/checkout@v7.0.0

    
      - name: compiling the java code
        run: javac Test.java

      - name: execting java code
        run: java Test
